Noah/Barometer_Drivers
UC-SOAR/PeripheralDriversSubmodule pull request #4
Opened 2024-11-16 21:10 UTC by NoahVickerson

Created the drivers for MS5611 and MS5607 Barometers

To test:
* Create a loop that periodically gets samples from the barometers and logs/records them
* Verify the readings are correct

To integrate:
* include the required header file
* declare an object of the class with the spi handle and required pins in the constructor
* call getSample() to return a data structure containing temp and pressure readings

2024-12-07 17:25 UTC, connellr023 requested changes

2024-12-07 17:25 UTC, connellr023 commented on MS5607Driver/Inc/MS5607Driver.hpp
> +	bool SetRegister(MS5607_REGISTER_t reg, uint8_t val);
C++ function naming convention is functions should be either be snake case (snake_case) or camel case starting with lowercase (camelCase).

2024-12-07 17:25 UTC, connellr023 commented on MS5607Driver/MS5607Driver.cpp
> +static uint8_t ADC_D1_512_CONV_CMD = 0x42;
Is there a reason these are static? Can they not be constexpr?

2024-12-07 17:25 UTC, connellr023 commented on MS5611Driver/MS5611Driver.cpp
> +static uint8_t ADC_D1_512_CONV_CMD = 0x42;
Same thing here, I believe these can be made constexpr.

2024-12-07 17:25 UTC, connellr023 commented on MS5607Driver/MS5607Driver.cpp
> +constexpr int TEMP_LOW = 2000;
These should be defined in a header file so that they *could* be shared across other files if we wanted to do that later.

2024-12-07 17:25 UTC, connellr023 commented on MS5607Driver/MS5607Driver.cpp
> +MS5607_DATA_t MS5607_Driver::getSample(){
This function could be split into multiple functions to improve readability rather than relying on comments.

2024-12-07 17:25 UTC, connellr023 commented on MS5611Driver/MS5611Driver.cpp
> +MS5611_DATA_t MS5611_Driver::getSample(){
This could also be split up in to multiple functions.

2025-01-04 18:17 UTC, NoahVickerson commented on MS5607Driver/MS5607Driver.cpp
> +static uint8_t ADC_D1_512_CONV_CMD = 0x42;
HAL freaks out if they are const, although they should not be changed.

2026-01-27 00:11 UTC, merged